/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.Main.jTableEventos;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Evento;
import sql.EventoDAO;

/**
 *
 * @author mayck
 */
public class AlterarEvento extends javax.swing.JDialog {

    String linhaEvento;
    public AlterarEvento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        labelMessage.setVisible(false);
    }
    
    public void AlterarEvento()
    {
        if(txtNome.getText().isEmpty())
        {
            labelMessage.setText("Insira um nome para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else if(txtCh.getText().isEmpty())
        {
            labelMessage.setText("Insira uma carga horária para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else if(txtData.getText().equals("  /  /    "))
        {
            labelMessage.setText("Insira uma data para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else
        {
            Evento e = new Evento();
            EventoDAO eD = new EventoDAO();

            e.setNomeEvento(txtNome.getText());
            e.setTipoEvento(txtTipoEvento.getText());
            e.setChEvento(txtCh.getText());
            e.setDataEvento(txtData.getText());
            e.setLocalEvento(txtLocal.getText());
            e.setAnoEvento(Integer.parseInt(spinnerAno.getValue().toString()));

            if(eD.alterarEvento(e,linhaEvento))
            {
                dispose();
                eD.getEvento("");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar o evento!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        data = new javax.swing.JLabel();
        adicionar = new javax.swing.JButton();
        txtCh = new javax.swing.JTextField();
        nome1 = new javax.swing.JLabel();
        labelMessage = new javax.swing.JLabel();
        cadastrarAluno = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        tipoEvento = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        spinnerAno = new javax.swing.JSpinner();
        btnCadastrar = new javax.swing.JLabel();
        txtTipoEvento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar evento");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome.setText("Nome");
        getContentPane().add(nome);
        nome.setBounds(40, 130, 60, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(40, 150, 410, 30);

        data.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        data.setText("Data");
        getContentPane().add(data);
        data.setBounds(40, 250, 80, 20);

        adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        adicionar.setText("Salvar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });
        getContentPane().add(adicionar);
        adicionar.setBounds(330, 420, 130, 30);
        getContentPane().add(txtCh);
        txtCh.setBounds(40, 210, 80, 30);

        nome1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome1.setText("CH");
        getContentPane().add(nome1);
        nome1.setBounds(40, 190, 70, 20);

        labelMessage.setBackground(new java.awt.Color(0, 204, 51));
        labelMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelMessage.setFocusable(false);
        labelMessage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelMessage.setOpaque(true);
        getContentPane().add(labelMessage);
        labelMessage.setBounds(0, 0, 490, 30);

        cadastrarAluno.setBackground(new java.awt.Color(204, 204, 204));
        cadastrarAluno.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        cadastrarAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarAluno.setText("Alterar evento");
        cadastrarAluno.setOpaque(true);
        getContentPane().add(cadastrarAluno);
        cadastrarAluno.setBounds(0, 0, 490, 60);
        getContentPane().add(txtData);
        txtData.setBounds(40, 270, 240, 30);

        tipoEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoEvento.setText("Tipo");
        getContentPane().add(tipoEvento);
        tipoEvento.setBounds(40, 70, 30, 20);

        labelLocal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLocal.setText("Local");
        getContentPane().add(labelLocal);
        labelLocal.setBounds(40, 310, 60, 20);
        getContentPane().add(txtLocal);
        txtLocal.setBounds(40, 330, 420, 30);

        spinnerAno.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerAno, "####"));
        getContentPane().add(spinnerAno);
        spinnerAno.setBounds(40, 390, 80, 30);

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrar.setText("Ano");
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(40, 370, 70, 20);
        getContentPane().add(txtTipoEvento);
        txtTipoEvento.setBounds(40, 90, 210, 30);

        jLabel1.setText("Ex: Palestra, Minicurso,Visita Técnica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 90, 220, 30);

        setBounds(0, 0, 498, 501);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
            AlterarEvento();        
    }//GEN-LAST:event_adicionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Main.linha_selecionada = jTableEventos.getSelectedRow();
        linhaEvento = String.valueOf(jTableEventos.getValueAt(Main.linha_selecionada, 0));
        txtNome.setText(String.valueOf(jTableEventos.getValueAt(Main.linha_selecionada, 1)));
        txtTipoEvento.setText(String.valueOf(jTableEventos.getValueAt(Main.linha_selecionada, 2)));
        txtData.setText(String.valueOf(jTableEventos.getValueAt(Main.linha_selecionada, 3)));
        txtCh.setText(String.valueOf(jTableEventos.getValueAt(Main.linha_selecionada, 4)));
        txtLocal.setText(String.valueOf(jTableEventos.getValueAt(Main.linha_selecionada, 7)));
        spinnerAno.setValue(Integer.parseInt(jTableEventos.getValueAt(Main.linha_selecionada, 8).toString()));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarEvento dialog = new AlterarEvento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JLabel btnCadastrar;
    private javax.swing.JLabel cadastrarAluno;
    private javax.swing.JLabel data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelLocal;
    public static javax.swing.JLabel labelMessage;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nome1;
    private javax.swing.JSpinner spinnerAno;
    private javax.swing.JLabel tipoEvento;
    private javax.swing.JTextField txtCh;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTipoEvento;
    // End of variables declaration//GEN-END:variables
}
