/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Evento;
import model.Participante;
import sql.EventoDAO;
import sql.ParticipanteDAO;

/**
 *
 * @author mayck
 */
public class CadastrarParticipante extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarEvento
     */
    public CadastrarParticipante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        labelMessage.setVisible(false);
    }
    
    public void inserirParticipante()
    {
        if(txtNome.getText().isEmpty())
        {
            labelMessage.setText("Insira um nome para o participante");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else if(txtEmail.getText().isEmpty())
        {
            labelMessage.setText("Insira um email para o participante");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else
        {
        Participante p = new Participante();
        ParticipanteDAO pD = new ParticipanteDAO();
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); 
        Date date = new Date();
        
        p.setNomeParticipante(txtNome.getText());
        p.setEmailParticipante(txtEmail.getText());
        p.setAlteracaoParticipante(String.valueOf(dateFormat.format(date)));
        
        if(pD.inserirParticipante(Main.linhaEvento, p))
        {
            dispose();
            pD.getParticipantes(Main.linhaEvento,"");
        }else{
        }
        
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        nome2 = new javax.swing.JLabel();
        adicionar = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        cadastrarAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar participante");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        getContentPane().setLayout(null);

        nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome.setText("Nome");
        getContentPane().add(nome);
        nome.setBounds(50, 90, 40, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(50, 120, 300, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(50, 190, 300, 30);

        nome2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome2.setText("Email");
        getContentPane().add(nome2);
        nome2.setBounds(50, 160, 40, 20);

        adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar.png"))); // NOI18N
        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });
        getContentPane().add(adicionar);
        adicionar.setBounds(250, 270, 120, 30);

        labelMessage.setBackground(new java.awt.Color(0, 204, 51));
        labelMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelMessage.setFocusable(false);
        labelMessage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelMessage.setOpaque(true);
        getContentPane().add(labelMessage);
        labelMessage.setBounds(0, 0, 410, 20);

        cadastrarAluno.setBackground(new java.awt.Color(204, 204, 204));
        cadastrarAluno.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        cadastrarAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarAluno.setText("Adicionar participante");
        cadastrarAluno.setOpaque(true);
        getContentPane().add(cadastrarAluno);
        cadastrarAluno.setBounds(0, 0, 420, 60);

        setBounds(0, 0, 416, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        inserirParticipante();
    }//GEN-LAST:event_adicionarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarParticipante dialog = new CadastrarParticipante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JLabel cadastrarAluno;
    public static javax.swing.JLabel labelMessage;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nome2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
