/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Evento;
import sql.EventoDAO;

/**
 *
 * @author mayck
 */
public class CadastrarEvento extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarEvento
     */
    int anoTop;
    public CadastrarEvento(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        labelMessage.setVisible(false);
        
        Date dataSpinner =  new Date();
        SimpleDateFormat formatoAno = new SimpleDateFormat("yyyy");
        String ano = formatoAno.format(dataSpinner);
       // anoTop = Integer.parseInt(ano);
        spinnerAno.setValue(Integer.parseInt(ano));
    }
    
    public void cadastrarEvento()
    {
        if(txtNome.getText().isEmpty())
        {
            labelMessage.setText("Insira um nome para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else if(txtCh.getText().isEmpty())
        {
            labelMessage.setText("Insira uma carga horária para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else if(txtData.getText().isEmpty())
        {
            labelMessage.setText("Insira uma data para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }
        else if(txtLocal.getText().isEmpty())
        {
            labelMessage.setText("Insira uma local para o evento");
            labelMessage.setBackground(new Color(255,102,0));           
            labelMessage.setVisible(true);
        }else
        {
        Evento e = new Evento();
        EventoDAO eD = new EventoDAO();
        
        e.setTipoEvento(txtTipoEvento.getText());
        e.setNomeEvento(txtNome.getText());
        e.setChEvento(txtCh.getText());
        e.setDataEvento(txtData.getText());
        e.setLocalEvento(txtLocal.getText());
        e.setAnoEvento((int) spinnerAno.getValue());
        
        if(eD.inserirEvento(e))
        {
            dispose();
            eD.getEvento("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar o evento!");
        }
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMessage = new javax.swing.JLabel();
        cadastrarAluno = new javax.swing.JLabel();
        tipoEvento = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        CH = new javax.swing.JLabel();
        txtCh = new javax.swing.JTextField();
        data = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        labelLocal = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        labelAno = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JLabel();
        spinnerAno = new javax.swing.JSpinner();
        txtTipoEvento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar evento");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        getContentPane().setLayout(null);

        labelMessage.setBackground(new java.awt.Color(0, 204, 51));
        labelMessage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelMessage.setFocusable(false);
        labelMessage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelMessage.setOpaque(true);
        getContentPane().add(labelMessage);
        labelMessage.setBounds(0, 0, 530, 30);

        cadastrarAluno.setBackground(new java.awt.Color(204, 204, 204));
        cadastrarAluno.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        cadastrarAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrarAluno.setText("Cadastrar evento");
        cadastrarAluno.setOpaque(true);
        getContentPane().add(cadastrarAluno);
        cadastrarAluno.setBounds(0, 0, 530, 60);

        tipoEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipoEvento.setText("Tipo");
        getContentPane().add(tipoEvento);
        tipoEvento.setBounds(50, 70, 40, 20);

        nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome.setText("Nome");
        getContentPane().add(nome);
        nome.setBounds(50, 130, 40, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(50, 150, 410, 30);

        CH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CH.setText("Carga Horária");
        getContentPane().add(CH);
        CH.setBounds(50, 190, 120, 20);
        getContentPane().add(txtCh);
        txtCh.setBounds(50, 210, 90, 30);

        data.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        data.setText("Data");
        getContentPane().add(data);
        data.setBounds(50, 250, 70, 20);
        getContentPane().add(txtData);
        txtData.setBounds(50, 270, 210, 30);

        labelLocal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLocal.setText("Local");
        getContentPane().add(labelLocal);
        labelLocal.setBounds(50, 310, 60, 20);
        getContentPane().add(txtLocal);
        txtLocal.setBounds(50, 330, 420, 30);

        labelAno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar.png"))); // NOI18N
        labelAno.setText("Cadastrar");
        labelAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelAnoActionPerformed(evt);
            }
        });
        getContentPane().add(labelAno);
        labelAno.setBounds(380, 450, 120, 30);

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrar.setText("Ano");
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(50, 370, 60, 20);

        spinnerAno.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerAno, "####"));
        getContentPane().add(spinnerAno);
        spinnerAno.setBounds(50, 390, 80, 30);
        getContentPane().add(txtTipoEvento);
        txtTipoEvento.setBounds(50, 90, 210, 30);

        jLabel1.setText("Ex: Palestra, Minicurso,Visita Técnica");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 90, 240, 30);

        setBounds(0, 0, 527, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void labelAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelAnoActionPerformed
        cadastrarEvento();
    }//GEN-LAST:event_labelAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarEvento dialog = new CadastrarEvento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CH;
    private javax.swing.JLabel btnCadastrar;
    private javax.swing.JLabel cadastrarAluno;
    private javax.swing.JLabel data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton labelAno;
    private javax.swing.JLabel labelLocal;
    public static javax.swing.JLabel labelMessage;
    private javax.swing.JLabel nome;
    private javax.swing.JSpinner spinnerAno;
    private javax.swing.JLabel tipoEvento;
    private javax.swing.JTextField txtCh;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTipoEvento;
    // End of variables declaration//GEN-END:variables
}
