
package interfaces;

import static interfaces.GerarCertificado.txtLivro;
import static interfaces.GerarCertificado.txtPagina;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Usuario;
import sql.ExportarExcel;
import sql.RegistroDAO;

/**
 *
 * @author mayck
 */
public class RegistroDigital extends javax.swing.JDialog {

    /**
     * Creates new form Relatorios
     */
    RegistroDAO registro = new RegistroDAO();
    static int linha_selecionada = 0;
    static String linhaRegistro = "0" ;
    
    public RegistroDigital(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents(); 
        txtLivro.setText(registro.getMaiorLivro());
        txtPagina.setText(registro.getMaiorPagina(registro.getMaiorLivro()));
        registro.getRegistro("",txtLivro.getText(),txtPagina.getText());
    }
    public void removerRegistro()
    {
       int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover esse registro?", "Remover registro", JOptionPane.YES_NO_OPTION);

        switch (resposta) 
        {
            case 0:
                RegistroDAO registro = new RegistroDAO();
                registro.deletarRegistro(linhaRegistro);
                linhaRegistro = "0";
                registro.getRegistro("",txtLivro.getText(),txtPagina.getText());
                break;
            case 1:
                break;
            default:
                break;
        }
      }
    
    
        
    public void exportar()
    {
        if(RegistroDigital.jTableRegistroDigital.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(null, "Não há dados na tabela para exportar.","Mayck Lima",JOptionPane.INFORMATION_MESSAGE);
        }else
        {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de excel","xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar arquivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        
        if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION)
        {
            List<JTable> tb = new ArrayList<>();
            List<String> nome = new ArrayList<>();
            tb.add(jTableRegistroDigital);
            nome.add("Registro Digital");
            String file = chooser.getSelectedFile().toString().concat(".xls");
            
            try {
                ExportarExcel e = new ExportarExcel(new File(file),tb,nome);
                if(e.exportar()){
                JOptionPane.showMessageDialog(null, "Os dados foram exportados");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
            
    }
    public void editar()
    {        
        if(linhaRegistro.equals("0"))
        {
            labelMensagem.setVisible(true);
            labelMensagem.setText("Selecione uma linha");
            labelMensagem.setBackground(new Color(255,102,0));
        }else
        {
            JFrame mainFrame = new JFrame();
            AlterarRegistro alterarRegistro = new AlterarRegistro(mainFrame, true);
            alterarRegistro.setLocationRelativeTo(mainFrame);
            alterarRegistro.setVisible(true);
        }
    }
    public void enviar()
    {
        JFrame mainFrame = new JFrame();
        EnviarEmail enviar = new EnviarEmail(mainFrame, true);
        enviar.setLocationRelativeTo(mainFrame);
        enviar.setVisible(true);
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        menuEnviar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuRemover = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistroDigital = new javax.swing.JTable();
        labelLivro = new javax.swing.JLabel();
        txtPesquisarRegistro = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        exportar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        labelMensagem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelRegistro = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        txtLivro = new javax.swing.JTextField();
        btnNextLivro = new javax.swing.JButton();
        btnPreviousLivro = new javax.swing.JButton();
        btnNextPagina = new javax.swing.JButton();
        txtPagina = new javax.swing.JTextField();
        btnPreviousPagina = new javax.swing.JButton();
        labelLivro1 = new javax.swing.JLabel();
        btnEnviar1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        menuEnviar.setText("Enviar por email...");
        menuEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnviarActionPerformed(evt);
            }
        });
        popUp.add(menuEnviar);

        menuEditar.setText("Editar registro");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        popUp.add(menuEditar);

        menuRemover.setText("Remover registro");
        menuRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoverActionPerformed(evt);
            }
        });
        popUp.add(menuRemover);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Digital - DirEx");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);

        jTableRegistroDigital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRegistroDigital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegistroDigitalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableRegistroDigitalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRegistroDigitalMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRegistroDigital);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 1230, 460);

        labelLivro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLivro.setText("Livro");
        getContentPane().add(labelLivro);
        labelLivro.setBounds(40, 70, 60, 20);

        txtPesquisarRegistro.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisarRegistro.setText("Pesquisar...");
        txtPesquisarRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarRegistroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisarRegistroFocusLost(evt);
            }
        });
        txtPesquisarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarRegistroActionPerformed(evt);
            }
        });
        txtPesquisarRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarRegistroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarRegistroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisarRegistroKeyTyped(evt);
            }
        });
        getContentPane().add(txtPesquisarRegistro);
        txtPesquisarRegistro.setBounds(830, 40, 350, 30);

        btnPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnPesquisar.setToolTipText("Clique para pesquisar por um registro");
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(1180, 40, 60, 30);

        exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        exportar.setText("Exportar");
        exportar.setToolTipText("Clique para exportar a tabela de registros");
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });
        getContentPane().add(exportar);
        exportar.setBounds(1140, 80, 100, 30);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar.png"))); // NOI18N
        btnAdicionar.setText("Adicionar registro");
        btnAdicionar.setToolTipText("Clique para adicionar um registro");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(330, 590, 160, 32);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar registro");
        btnEditar.setToolTipText("Clique para editar um registro");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(510, 590, 160, 32);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deleteProjeto.png"))); // NOI18N
        btnRemover.setText("Remover registro");
        btnRemover.setToolTipText("Clique para remover um registro");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemover);
        btnRemover.setBounds(690, 590, 160, 32);

        labelMensagem.setBackground(new java.awt.Color(0, 204, 51));
        labelMensagem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMensagem.setForeground(new java.awt.Color(255, 255, 255));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setFocusable(false);
        labelMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelMensagem.setOpaque(true);
        getContentPane().add(labelMensagem);
        labelMensagem.setBounds(0, 0, 1270, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 1270, 10);

        labelRegistro.setBackground(new java.awt.Color(204, 204, 204));
        labelRegistro.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        labelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistro.setText("Registro digital");
        labelRegistro.setOpaque(true);
        getContentPane().add(labelRegistro);
        labelRegistro.setBounds(0, -10, 1260, 80);

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sendemail.png"))); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(1100, 590, 130, 32);
        getContentPane().add(txtLivro);
        txtLivro.setBounds(40, 90, 40, 30);

        btnNextLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btnNextLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextLivroActionPerformed(evt);
            }
        });
        getContentPane().add(btnNextLivro);
        btnNextLivro.setBounds(80, 90, 30, 30);

        btnPreviousLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        btnPreviousLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousLivroActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreviousLivro);
        btnPreviousLivro.setBounds(10, 90, 30, 30);

        btnNextPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btnNextPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPaginaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNextPagina);
        btnNextPagina.setBounds(230, 90, 30, 30);
        getContentPane().add(txtPagina);
        txtPagina.setBounds(190, 90, 40, 30);

        btnPreviousPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        btnPreviousPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousPaginaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreviousPagina);
        btnPreviousPagina.setBounds(160, 90, 30, 30);

        labelLivro1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLivro1.setText("Página");
        getContentPane().add(labelLivro1);
        labelLivro1.setBounds(190, 70, 60, 20);

        btnEnviar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btnEnviar1.setText("Abrir/Imprimir");
        btnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar1);
        btnEnviar1.setBounds(950, 590, 130, 32);

        bg.setBackground(new java.awt.Color(236, 236, 236));
        bg.setOpaque(true);
        getContentPane().add(bg);
        bg.setBounds(0, -6, 1270, 650);

        setBounds(0, 0, 1268, 672);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroActionPerformed

    }//GEN-LAST:event_txtPesquisarRegistroActionPerformed

    private void txtPesquisarRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroKeyPressed
        registro.getRegistro(txtPesquisarRegistro.getText(),txtLivro.getText(),txtPagina.getText());
        linhaRegistro = "0";
    }//GEN-LAST:event_txtPesquisarRegistroKeyPressed

    private void txtPesquisarRegistroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroKeyReleased
        registro.getRegistro(txtPesquisarRegistro.getText(),txtLivro.getText(),txtPagina.getText());
         linhaRegistro = "0";
    }//GEN-LAST:event_txtPesquisarRegistroKeyReleased

    private void txtPesquisarRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroKeyTyped
        registro.getRegistro(txtPesquisarRegistro.getText(),txtLivro.getText(),txtPagina.getText());
         linhaRegistro = "0";
    }//GEN-LAST:event_txtPesquisarRegistroKeyTyped

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        registro.getRegistro(txtPesquisarRegistro.getText(),txtLivro.getText(),txtPagina.getText());
        linhaRegistro = "0";
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
      exportar();
    }//GEN-LAST:event_exportarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        JFrame mainFrame = new JFrame();
        CadastrarRegistro ad = new CadastrarRegistro(mainFrame, true);
        ad.setLocationRelativeTo(mainFrame);
        ad.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
      if(linhaRegistro.equals("0"))
      {
          labelMensagem.setVisible(true);
          labelMensagem.setText("Selecione uma linha");
          labelMensagem.setBackground(new Color(255,102,0));
      }else{
        removerRegistro();
      }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void jTableRegistroDigitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroDigitalMouseClicked
           if(jTableRegistroDigital.getSelectedRow() >= 0)
            {
                linha_selecionada = jTableRegistroDigital.getSelectedRow();
                linhaRegistro = (String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 0)));
                labelMensagem.setVisible(false);
            }else
            {
            }  
    }//GEN-LAST:event_jTableRegistroDigitalMouseClicked

    private void jTableRegistroDigitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroDigitalMousePressed
            if(jTableRegistroDigital.getSelectedRow() >= 0)
            {
                linha_selecionada = jTableRegistroDigital.getSelectedRow();
                linhaRegistro = (String.valueOf(jTableRegistroDigital.getValueAt(linha_selecionada, 0)));
                labelMensagem.setVisible(false);
            }else
            {
            }  
    }//GEN-LAST:event_jTableRegistroDigitalMousePressed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        editar();
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoverActionPerformed
        removerRegistro();
    }//GEN-LAST:event_menuRemoverActionPerformed

    private void jTableRegistroDigitalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegistroDigitalMouseReleased
    if(jTableRegistroDigital.getSelectedRow() >= 0)
    {  
        if(evt.isPopupTrigger())
        {
            popUp.show(jTableRegistroDigital, evt.getX(), evt.getY()); 
            labelMensagem.setVisible(false);
        }
    }else
    {
    }
    }//GEN-LAST:event_jTableRegistroDigitalMouseReleased

    private void menuEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnviarActionPerformed
    enviar();
        
    }//GEN-LAST:event_menuEnviarActionPerformed

    private void txtPesquisarRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroFocusGained
        txtPesquisarRegistro.setText("");
        txtPesquisarRegistro.setForeground(Color.black);
        labelMensagem.setVisible(false);
    }//GEN-LAST:event_txtPesquisarRegistroFocusGained

    private void txtPesquisarRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarRegistroFocusLost
        txtPesquisarRegistro.setText("Pesquisar...");
        txtPesquisarRegistro.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtPesquisarRegistroFocusLost

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
          if(linhaRegistro.equals("0"))
        {
            labelMensagem.setVisible(true);
            labelMensagem.setText("Selecione uma linha");
            labelMensagem.setBackground(new Color(255,102,0));
        }else
          {
            enviar();
          }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnPreviousLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousLivroActionPerformed
       int n_livro = Integer.parseInt(txtLivro.getText()) - 1;
       if(n_livro >= 1)
       {
        txtLivro.setText(String.valueOf(n_livro));
        if(registro.getMaiorPagina(String.valueOf(n_livro)) == null){
            txtPagina.setText("1");
        }else{
            txtPagina.setText(registro.getMaiorPagina(String.valueOf(n_livro)));
        }   
        registro.getRegistro("",txtLivro.getText(),registro.getMaiorPagina(txtLivro.getText()));
       }else
       { 
       }
    }//GEN-LAST:event_btnPreviousLivroActionPerformed

    private void btnNextLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextLivroActionPerformed
        int n_livro = Integer.parseInt(txtLivro.getText()) + 1;       
        txtLivro.setText(String.valueOf(n_livro));
        
        if(registro.getMaiorPagina(String.valueOf(n_livro)) == null){
            txtPagina.setText("1");
        }else{
            txtPagina.setText(registro.getMaiorPagina(String.valueOf(n_livro)));
        }        
        registro.getRegistro("",txtLivro.getText(),registro.getMaiorPagina(String.valueOf(n_livro)));
    }//GEN-LAST:event_btnNextLivroActionPerformed

    private void btnPreviousPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousPaginaActionPerformed
        int n_pagina = Integer.parseInt(txtPagina.getText());
        if(n_pagina > 1)
        {
            txtPagina.setText(String.valueOf(n_pagina - 1));
            registro.getRegistro("",txtLivro.getText(),txtPagina.getText());
        }else
        { 
        }
    }//GEN-LAST:event_btnPreviousPaginaActionPerformed

    private void btnNextPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPaginaActionPerformed
        int n_pagina = Integer.parseInt(txtPagina.getText());
        txtPagina.setText(String.valueOf(n_pagina + 1));
        registro.getRegistro("",txtLivro.getText(),txtPagina.getText());
    }//GEN-LAST:event_btnNextPaginaActionPerformed

    private void btnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar1ActionPerformed
        if(linhaRegistro.equals("0"))
        {
            labelMensagem.setVisible(true);
            labelMensagem.setText("Selecione uma linha");
            labelMensagem.setBackground(new Color(255,102,0));
        }else{
            try 
            {
                File diretorio = new File(Usuario.getSalvar_em() + "\\" + String.valueOf(jTableRegistroDigital.getValueAt(RegistroDigital.linha_selecionada, 3)));
                Desktop.getDesktop().open(new File(diretorio + "\\"  + Integer.parseInt(String.valueOf(jTableRegistroDigital.getValueAt(RegistroDigital.linha_selecionada, 1))) + "-" + String.valueOf(jTableRegistroDigital.getValueAt(RegistroDigital.linha_selecionada, 2) + ".pdf")));
            } catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado");
            }            
        }
        
        
    }//GEN-LAST:event_btnEnviar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroDigital dialog = new RegistroDigital(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JButton btnNextLivro;
    private javax.swing.JButton btnNextPagina;
    private static javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPreviousLivro;
    private javax.swing.JButton btnPreviousPagina;
    public javax.swing.JButton btnRemover;
    private javax.swing.JButton exportar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTableRegistroDigital;
    private javax.swing.JLabel labelLivro;
    private javax.swing.JLabel labelLivro1;
    public static javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuEnviar;
    private javax.swing.JMenuItem menuRemover;
    private javax.swing.JPopupMenu popUp;
    public static javax.swing.JTextField txtLivro;
    public static javax.swing.JTextField txtPagina;
    private javax.swing.JTextField txtPesquisarRegistro;
    // End of variables declaration//GEN-END:variables
}
